- name: Install and configure nginx web server
  hosts: wiki
  collections:
    - nginxinc.nginx_controller
  gather_facts: true
  roles:
    - role: nginx
      vars:
        nginx_enable: true
        nginx_start: true
        nginx_type: plus
